- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - tempest-plugin-jobs
    check:
      jobs:
        - trove-tempest-plugin:
            voting: false
        - trove-tempest-ipv6-only:
            voting: false
    gate:
      queue: trove
      jobs:
        - trove-tempest-plugin:
            voting: false
        - trove-tempest-ipv6-only:
            voting: false

- job:
    name: trove-tempest-plugin
    parent: devstack-tempest
    timeout: 7800
    description: |
      This job is for stable branch prior to Ussuri for testing
      on py2.
    required-projects:
      - openstack/neutron
      - openstack/trove
      - openstack/trove-tempest-plugin
      - openstack/tempest
    vars:
      tox_envlist: all
      devstack_localrc:
        TEMPEST_PLUGINS: /opt/stack/trove-tempest-plugin
        USE_PYTHON3: False
      devstack_plugins:
        trove: https://opendev.org/openstack/trove
      devstack_services:
        tempest: true
        tls-proxy: false
      tempest_test_regex: ^trove_tempest_plugin\.tests.scenario\.test_instance_basic\.TestInstanceBasicMySQL\.test_database_access
    branches:
      - stable/ocata
      - stable/pike
      - stable/queens
      - stable/rocky
      - stable/stein
      - stable/train

- job:
    name: trove-tempest-plugin
    parent: devstack-tempest
    nodeset: trove-ubuntu-focal
    timeout: 10800
    description: |
      This job is for testing on py3 which is Ussuri onwards.
    required-projects: &base_required_projects
      - openstack/trove
      - openstack/trove-tempest-plugin
      - openstack/tempest
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^releasenotes/.*$
    vars: &base_vars
      tox_envlist: all
      tempest_concurrency: 1
      devstack_localrc:
        TEMPEST_PLUGINS: /opt/stack/trove-tempest-plugin
        USE_PYTHON3: true
        Q_AGENT: openvswitch
        Q_PLUGIN: ml2
        Q_ML2_TENANT_NETWORK_TYPE: vxlan
        Q_ML2_PLUGIN_MECHANISM_DRIVERS: openvswitch
      devstack_local_conf:
        post-config:
          $TROVE_CONF:
            DEFAULT:
              usage_timeout: 1800
      devstack_plugins:
        trove: https://opendev.org/openstack/trove.git
      devstack_services:
        etcd3: false
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
        cinder: true
        c-sch: true
        c-api: true
        c-vol: true
        c-bak: false
        swift: true
        s-account: true
        s-container: true
        s-object: true
        s-proxy: true
        tempest: true
        q-svc: true
        q-agt: true
        q-dhcp: true
        q-l3: true
        q-meta: true
        q-ovn-metadata-agent: false
        ovn-controller: false
        ovn-northd: false
      tempest_test_regex: ^trove_tempest_plugin\.tests
      tempest_test_blacklist: '{{ ansible_user_dir }}/{{ zuul.projects["opendev.org/openstack/trove-tempest-plugin"].src_dir }}/tempest_blacklist.txt'

- job:
    name: trove-tempest-ipv6-only
    parent: devstack-tempest-ipv6
    description: |
      Trove devstack tempest tests job for IPv6-only deployment
    required-projects: *base_required_projects
    vars: *base_vars
